# Deploy function to firebase 

name: Deploy to firebase function

on:
  push:
    branches:
    - master
jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g firebase-tools
      - name: deploy functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./.github/scripts/deploy.sh
